### ISSUE TITLE
Complete Vim Adventures

### ISSUE THREAD

**Issue by skrpt** [feynman-project/phil-onboarding#1]
- [ ] Complete level 1

**Comment by PhilipWilburn** [comment]
Levels 1-3 complete! I recieved delish Bday cake!

**Comment by skrpt** [comment]
@PhilipWilburn How's your status?

**Comment by PhilipWilburn** [comment]
I complete it but I still do not have Admin permission to move issue to review.

**Comment by skrpt** [comment]
@PhilipWilburn I updated you to Team Maintainer in the org privileges. Issues can only be closed by the original creator of the repo. I'll close this issue, thanks for completing the task.
